# Generated by Django 3.1 on 2021-05-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_auto_20210504_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='items',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
