# Generated by Django 3.1 on 2021-05-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0006_auto_20210504_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='menu', to='canteen.OrderItem'),
        ),
    ]
