# Generated by Django 3.1 on 2021-05-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0007_auto_20210504_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_shipped', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(blank=True, related_name='menu', to='canteen.Product')),
            ],
        ),
    ]
